
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

import java_cup.runtime.*;
import java.io.*;
import java.util.*;
import misc.TokenInfo;
import ast.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\103\000\002\002\004\000\002\002\007\000\002\003" +
    "\006\000\002\004\005\000\002\005\003\000\002\005\004" +
    "\000\002\006\013\000\002\006\007\000\002\006\011\000" +
    "\002\006\007\000\002\006\011\000\002\006\017\000\002" +
    "\006\010\000\002\006\010\000\002\006\004\000\002\006" +
    "\004\000\002\006\004\000\002\007\003\000\002\007\005" +
    "\000\002\007\005\000\002\013\003\000\002\013\005\000" +
    "\002\013\002\000\002\014\004\000\002\012\003\000\002" +
    "\012\005\000\002\012\002\000\002\010\003\000\002\010" +
    "\005\000\002\011\003\000\002\011\006\000\002\011\005" +
    "\000\002\021\003\000\002\021\003\000\002\023\003\000" +
    "\002\023\003\000\002\023\003\000\002\023\003\000\002" +
    "\023\003\000\002\022\003\000\002\022\003\000\002\022" +
    "\003\000\002\015\006\000\002\016\005\000\002\017\004" +
    "\000\002\024\003\000\002\024\003\000\002\024\003\000" +
    "\002\025\003\000\002\025\003\000\002\027\003\000\002" +
    "\027\003\000\002\027\003\000\002\027\003\000\002\027" +
    "\003\000\002\027\003\000\002\026\003\000\002\026\003" +
    "\000\002\026\003\000\002\026\003\000\002\030\003\000" +
    "\002\030\003\000\002\030\003\000\002\020\003\000\002" +
    "\020\003\000\002\020\003\000\002\020\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\004\006\006\001\002\000\004\004\014\001" +
    "\002\000\004\002\013\001\002\000\004\016\007\001\002" +
    "\000\004\054\010\001\002\000\004\017\011\001\002\000" +
    "\004\014\012\001\002\000\004\004\000\001\002\000\004" +
    "\002\001\001\002\000\004\020\016\001\002\000\004\005" +
    "\216\001\002\000\032\007\026\011\020\012\035\041\021" +
    "\042\037\043\040\044\017\045\030\047\025\050\036\051" +
    "\033\054\031\001\002\000\006\020\uffbf\054\uffbf\001\002" +
    "\000\004\054\211\001\002\000\006\020\uffc2\054\uffc2\001" +
    "\002\000\004\021\210\001\002\000\004\054\207\001\002" +
    "\000\004\015\206\001\002\000\004\016\202\001\002\000" +
    "\004\054\161\001\002\000\004\015\160\001\002\000\004" +
    "\016\152\001\002\000\010\030\131\031\133\032\132\001" +
    "\002\000\036\007\026\010\ufffd\011\020\012\035\021\ufffd" +
    "\041\021\042\037\043\040\044\017\045\030\047\025\050" +
    "\036\051\033\054\031\001\002\000\004\020\016\001\002" +
    "\000\004\015\142\001\002\000\004\054\135\001\002\000" +
    "\004\016\041\001\002\000\006\020\uffc0\054\uffc0\001\002" +
    "\000\006\020\uffc1\054\uffc1\001\002\000\014\041\021\042" +
    "\037\043\040\044\017\054\042\001\002\000\012\013\uffd8" +
    "\030\131\031\133\032\132\001\002\000\004\013\115\001" +
    "\002\000\004\054\047\001\002\000\004\013\uffda\001\002" +
    "\000\004\013\uffd9\001\002\000\004\030\050\001\002\000" +
    "\016\052\052\053\062\054\057\055\054\056\056\057\051" +
    "\001\002\000\040\013\uffdb\015\uffdb\017\uffdb\022\uffdb\023" +
    "\uffdb\024\uffdb\025\uffdb\026\uffdb\027\uffdb\033\uffdb\034\uffdb" +
    "\035\uffdb\036\uffdb\037\uffdb\040\uffdb\001\002\000\040\013" +
    "\uffdf\015\uffdf\017\uffdf\022\uffdf\023\uffdf\024\uffdf\025\uffdf" +
    "\026\uffdf\027\uffdf\033\uffdf\034\uffdf\035\uffdf\036\uffdf\037" +
    "\uffdf\040\uffdf\001\002\000\006\013\uffd7\015\uffd7\001\002" +
    "\000\040\013\uffdd\015\uffdd\017\uffdd\022\uffdd\023\uffdd\024" +
    "\uffdd\025\uffdd\026\uffdd\027\uffdd\033\uffdd\034\uffdd\035\uffdd" +
    "\036\uffdd\037\uffdd\040\uffdd\001\002\000\040\013\uffe6\015" +
    "\uffe6\017\uffe6\022\103\023\102\024\104\025\111\026\113" +
    "\027\105\033\100\034\112\035\065\036\063\037\064\040" +
    "\066\001\002\000\040\013\uffdc\015\uffdc\017\uffdc\022\uffdc" +
    "\023\uffdc\024\uffdc\025\uffdc\026\uffdc\027\uffdc\033\uffdc\034" +
    "\uffdc\035\uffdc\036\uffdc\037\uffdc\040\uffdc\001\002\000\042" +
    "\013\uffe1\015\uffe1\016\072\017\uffe1\022\uffe1\023\uffe1\024" +
    "\uffe1\025\uffe1\026\uffe1\027\uffe1\033\uffe1\034\uffe1\035\uffe1" +
    "\036\uffe1\037\uffe1\040\uffe1\001\002\000\040\013\uffe0\015" +
    "\uffe0\017\uffe0\022\uffe0\023\uffe0\024\uffe0\025\uffe0\026\uffe0" +
    "\027\uffe0\033\uffe0\034\uffe0\035\uffe0\036\uffe0\037\uffe0\040" +
    "\uffe0\001\002\000\040\013\uffe4\015\uffe4\017\uffe4\022\uffe4" +
    "\023\uffe4\024\uffe4\025\uffe4\026\uffe4\027\uffe4\033\uffe4\034" +
    "\uffe4\035\065\036\063\037\064\040\066\001\002\000\040" +
    "\013\uffde\015\uffde\017\uffde\022\uffde\023\uffde\024\uffde\025" +
    "\uffde\026\uffde\027\uffde\033\uffde\034\uffde\035\uffde\036\uffde" +
    "\037\uffde\040\uffde\001\002\000\016\052\uffc8\053\uffc8\054" +
    "\uffc8\055\uffc8\056\uffc8\057\uffc8\001\002\000\016\052\uffc7" +
    "\053\uffc7\054\uffc7\055\uffc7\056\uffc7\057\uffc7\001\002\000" +
    "\016\052\uffc9\053\uffc9\054\uffc9\055\uffc9\056\uffc9\057\uffc9" +
    "\001\002\000\016\052\uffc6\053\uffc6\054\uffc6\055\uffc6\056" +
    "\uffc6\057\uffc6\001\002\000\016\052\052\053\062\054\070" +
    "\055\054\056\056\057\051\001\002\000\040\013\uffe1\015" +
    "\uffe1\017\uffe1\022\uffe1\023\uffe1\024\uffe1\025\uffe1\026\uffe1" +
    "\027\uffe1\033\uffe1\034\uffe1\035\uffe1\036\uffe1\037\uffe1\040" +
    "\uffe1\001\002\000\040\013\uffe2\015\uffe2\017\uffe2\022\uffe2" +
    "\023\uffe2\024\uffe2\025\uffe2\026\uffe2\027\uffe2\033\uffe2\034" +
    "\uffe2\035\uffe2\036\uffe2\037\uffe2\040\uffe2\001\002\000\020" +
    "\017\uffe7\052\052\053\062\054\057\055\054\056\056\057" +
    "\051\001\002\000\006\013\076\017\uffe9\001\002\000\004" +
    "\017\075\001\002\000\040\013\uffe3\015\uffe3\017\uffe3\022" +
    "\uffe3\023\uffe3\024\uffe3\025\uffe3\026\uffe3\027\uffe3\033\uffe3" +
    "\034\uffe3\035\uffe3\036\uffe3\037\uffe3\040\uffe3\001\002\000" +
    "\020\017\uffe7\052\052\053\062\054\057\055\054\056\056" +
    "\057\051\001\002\000\004\017\uffe8\001\002\000\016\052" +
    "\uffd1\053\uffd1\054\uffd1\055\uffd1\056\uffd1\057\uffd1\001\002" +
    "\000\016\052\uffd4\053\uffd4\054\uffd4\055\uffd4\056\uffd4\057" +
    "\uffd4\001\002\000\016\052\uffce\053\uffce\054\uffce\055\uffce" +
    "\056\uffce\057\uffce\001\002\000\016\052\uffcf\053\uffcf\054" +
    "\uffcf\055\uffcf\056\uffcf\057\uffcf\001\002\000\016\052\uffcd" +
    "\053\uffcd\054\uffcd\055\uffcd\056\uffcd\057\uffcd\001\002\000" +
    "\016\052\uffca\053\uffca\054\uffca\055\uffca\056\uffca\057\uffca" +
    "\001\002\000\016\052\uffd3\053\uffd3\054\uffd3\055\uffd3\056" +
    "\uffd3\057\uffd3\001\002\000\016\052\uffd2\053\uffd2\054\uffd2" +
    "\055\uffd2\056\uffd2\057\uffd2\001\002\000\016\052\052\053" +
    "\062\054\057\055\054\056\056\057\051\001\002\000\016" +
    "\052\uffcc\053\uffcc\054\uffcc\055\uffcc\056\uffcc\057\uffcc\001" +
    "\002\000\016\052\uffd0\053\uffd0\054\uffd0\055\uffd0\056\uffd0" +
    "\057\uffd0\001\002\000\016\052\uffcb\053\uffcb\054\uffcb\055" +
    "\uffcb\056\uffcb\057\uffcb\001\002\000\010\013\uffe5\015\uffe5" +
    "\017\uffe5\001\002\000\016\052\052\053\062\054\057\055" +
    "\054\056\056\057\051\001\002\000\004\013\124\001\002" +
    "\000\026\013\ufff0\017\ufff0\022\103\023\102\024\104\025" +
    "\111\026\113\027\105\033\100\034\112\001\002\000\016" +
    "\052\052\053\062\054\057\055\054\056\056\057\051\001" +
    "\002\000\016\052\052\053\062\054\057\055\054\056\056" +
    "\057\051\001\002\000\006\013\uffee\017\uffee\001\002\000" +
    "\006\013\uffef\017\uffef\001\002\000\004\054\031\001\002" +
    "\000\004\017\126\001\002\000\004\020\016\001\002\000" +
    "\036\007\ufffb\010\ufffb\011\ufffb\012\ufffb\021\ufffb\041\ufffb" +
    "\042\ufffb\043\ufffb\044\ufffb\045\ufffb\047\ufffb\050\ufffb\051" +
    "\ufffb\054\ufffb\001\002\000\016\052\052\053\062\054\057" +
    "\055\054\056\056\057\051\001\002\000\016\052\uffc5\053" +
    "\uffc5\054\uffc5\055\uffc5\056\uffc5\057\uffc5\001\002\000\016" +
    "\052\uffc3\053\uffc3\054\uffc3\055\uffc3\056\uffc3\057\uffc3\001" +
    "\002\000\016\052\uffc4\053\uffc4\054\uffc4\055\uffc4\056\uffc4" +
    "\057\uffc4\001\002\000\010\013\uffd6\015\uffd6\017\uffd6\001" +
    "\002\000\004\016\136\001\002\000\020\017\uffe7\052\052" +
    "\053\062\054\057\055\054\056\056\057\051\001\002\000" +
    "\004\017\140\001\002\000\004\015\141\001\002\000\036" +
    "\007\ufff4\010\ufff4\011\ufff4\012\ufff4\021\ufff4\041\ufff4\042" +
    "\ufff4\043\ufff4\044\ufff4\045\ufff4\047\ufff4\050\ufff4\051\ufff4" +
    "\054\ufff4\001\002\000\036\007\ufff1\010\ufff1\011\ufff1\012" +
    "\ufff1\021\ufff1\041\ufff1\042\ufff1\043\ufff1\044\ufff1\045\ufff1" +
    "\047\ufff1\050\ufff1\051\ufff1\054\ufff1\001\002\000\004\047" +
    "\144\001\002\000\004\016\145\001\002\000\016\052\052" +
    "\053\062\054\057\055\054\056\056\057\051\001\002\000" +
    "\004\017\147\001\002\000\004\015\150\001\002\000\036" +
    "\007\ufff9\010\ufff9\011\ufff9\012\ufff9\021\ufff9\041\ufff9\042" +
    "\ufff9\043\ufff9\044\ufff9\045\ufff9\047\ufff9\050\ufff9\051\ufff9" +
    "\054\ufff9\001\002\000\006\010\ufffc\021\ufffc\001\002\000" +
    "\016\052\052\053\062\054\057\055\054\056\056\057\051" +
    "\001\002\000\004\017\154\001\002\000\004\020\016\001" +
    "\002\000\040\007\ufff8\010\ufff8\011\ufff8\012\ufff8\021\ufff8" +
    "\041\ufff8\042\ufff8\043\ufff8\044\ufff8\045\ufff8\046\156\047" +
    "\ufff8\050\ufff8\051\ufff8\054\ufff8\001\002\000\004\020\016" +
    "\001\002\000\036\007\ufff7\010\ufff7\011\ufff7\012\ufff7\021" +
    "\ufff7\041\ufff7\042\ufff7\043\ufff7\044\ufff7\045\ufff7\047\ufff7" +
    "\050\ufff7\051\ufff7\054\ufff7\001\002\000\036\007\ufff2\010" +
    "\ufff2\011\ufff2\012\ufff2\021\ufff2\041\ufff2\042\ufff2\043\ufff2" +
    "\044\ufff2\045\ufff2\047\ufff2\050\ufff2\051\ufff2\054\ufff2\001" +
    "\002\000\004\016\162\001\002\000\014\017\uffeb\041\021" +
    "\042\037\043\040\044\017\001\002\000\004\017\171\001" +
    "\002\000\004\054\170\001\002\000\006\013\166\017\uffed" +
    "\001\002\000\014\017\uffeb\041\021\042\037\043\040\044" +
    "\017\001\002\000\004\017\uffec\001\002\000\006\013\uffea" +
    "\017\uffea\001\002\000\004\014\172\001\002\000\012\041" +
    "\021\042\037\043\040\044\017\001\002\000\004\020\174" +
    "\001\002\000\032\007\026\011\020\012\035\041\021\042" +
    "\037\043\040\044\017\045\030\047\025\050\036\051\033" +
    "\054\031\001\002\000\004\010\176\001\002\000\016\052" +
    "\052\053\062\054\070\055\054\056\056\057\051\001\002" +
    "\000\004\015\200\001\002\000\004\021\201\001\002\000" +
    "\036\007\ufff6\010\ufff6\011\ufff6\012\ufff6\021\ufff6\041\ufff6" +
    "\042\ufff6\043\ufff6\044\ufff6\045\ufff6\047\ufff6\050\ufff6\051" +
    "\ufff6\054\ufff6\001\002\000\016\052\052\053\062\054\057" +
    "\055\054\056\056\057\051\001\002\000\004\017\204\001" +
    "\002\000\004\020\016\001\002\000\036\007\ufffa\010\ufffa" +
    "\011\ufffa\012\ufffa\021\ufffa\041\ufffa\042\ufffa\043\ufffa\044" +
    "\ufffa\045\ufffa\047\ufffa\050\ufffa\051\ufffa\054\ufffa\001\002" +
    "\000\036\007\ufff3\010\ufff3\011\ufff3\012\ufff3\021\ufff3\041" +
    "\ufff3\042\ufff3\043\ufff3\044\ufff3\045\ufff3\047\ufff3\050\ufff3" +
    "\051\ufff3\054\ufff3\001\002\000\006\015\uffd5\030\050\001" +
    "\002\000\042\005\ufffe\007\ufffe\010\ufffe\011\ufffe\012\ufffe" +
    "\021\ufffe\041\ufffe\042\ufffe\043\ufffe\044\ufffe\045\ufffe\046" +
    "\ufffe\047\ufffe\050\ufffe\051\ufffe\054\ufffe\001\002\000\004" +
    "\016\212\001\002\000\014\017\uffeb\041\021\042\037\043" +
    "\040\044\017\001\002\000\004\017\214\001\002\000\004" +
    "\020\016\001\002\000\036\007\ufff5\010\ufff5\011\ufff5\012" +
    "\ufff5\021\ufff5\041\ufff5\042\ufff5\043\ufff5\044\ufff5\045\ufff5" +
    "\047\ufff5\050\ufff5\051\ufff5\054\ufff5\001\002\000\004\002" +
    "\uffff\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\214\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\004\014\001\001\000\002\001\001" +
    "\000\016\005\021\006\031\015\023\016\026\017\033\020" +
    "\022\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\030\127\001\001\000\016\005" +
    "\150\006\031\015\023\016\026\017\033\020\022\001\001" +
    "\000\004\004\142\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\015\044\016\045\020\043\022\042\001\001\000" +
    "\004\030\127\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\010\052\011\054\021\060\023\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\024\107\025\100\026\105\027\106\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\026\066\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\021\070\023\057\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\011\072\012\073\021\060\023\057\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\011\072\012\076\021\060\023\057\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\010\113" +
    "\011\054\021\060\023\057\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\007\115\011\116\021\060\023\057\001\001\000\002\001" +
    "\001\000\006\025\117\027\120\001\001\000\012\007\122" +
    "\011\116\021\060\023\057\001\001\000\012\007\121\011" +
    "\116\021\060\023\057\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\124\001\001\000\002\001\001\000" +
    "\004\004\126\001\001\000\002\001\001\000\012\010\133" +
    "\011\054\021\060\023\057\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\011\072\012\136\021\060\023\057\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\012\007\145\011\116\021\060\023\057\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\007\152\011\116\021\060\023\057\001\001" +
    "\000\002\001\001\000\004\004\154\001\001\000\002\001" +
    "\001\000\004\004\156\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\013\162\014\164\020" +
    "\163\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\013\166\014\164\020\163\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\020\172\001\001\000\002\001\001\000\016\005\174\006" +
    "\031\015\023\016\026\017\033\020\022\001\001\000\002" +
    "\001\001\000\006\021\176\023\057\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\007\202" +
    "\011\116\021\060\023\057\001\001\000\002\001\001\000" +
    "\004\004\204\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\013\212\014\164\020\163\001\001\000\002\001\001" +
    "\000\004\004\214\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



//Comentários abaixo obtidos do manual (https://www.cs.princeton.edu/~appel/modern/java/CUP/manual.html)
/*
This method should be called whenever an error message is to be issued.
In the default implementation of this method, the first parameter provides the text of a
message which is printed on System.err and the second parameter is simply ignored.
It is very typical to override this method in order to provide a more sophisticated error reporting mechanism.
*/

    public void report_error(String message, Object info) {
            if (info instanceof Symbol) {
                Symbol symbol = (Symbol) info;
                TokenInfo tokenInfo = symbol.value instanceof TokenInfo ? (TokenInfo) symbol.value : null;

                if (tokenInfo != null) {
                    int linha = tokenInfo.linha;
                    int coluna = tokenInfo.coluna;
                    String lexema = tokenInfo.lexema;
                    System.err.println("Erro sintatico - linha: " + (linha + 1) + ", coluna " + (coluna + 1) + ", lexema: '"+ lexema +"' - " + message);
                } else {
                    System.err.println("Erro sintatico: " + message);
                }
            } else {
                System.err.println("Erro sintatico: " + message);
            }
        }
/*
This method should be called whenever a non-recoverable error occurs.
It responds by calling report_error(), then aborts parsing by calling the parser method done_parsing(),
and finally throws an exception. (In general done_parsing() should be called at any point that parsing needs to be terminated early).
*/
    public void report_fatal_error(String message, Object info) {
        report_error("Erro fatal: " + message, info);
        System.exit(1);
    }
/*
This method is called by the parser if it is unable to recover from a syntax error.
In the default implementation it calls: report_fatal_error("Couldn't repair and continue parse", null);.
*/
    public void unrecovered_syntax_error(Symbol cur_token) {
        report_fatal_error("O analisador lexico falhou e nao se recuperou", cur_token);
    }
/*
This method is called by the parser as soon as a syntax error is detected (but before error recovery is attempted).
In the default implementation it calls: report_error("Syntax error", null);.
*/
        public void syntax_error(Symbol cur_token){
            report_error("Erro sintatico", cur_token);
        }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ProgramaNode start_val = (ProgramaNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // init_programa ::= PROGRAMA L_PARENTESES ID R_PARENTESES DOIS_PONTOS 
            {
              InitProgramaNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		TokenInfo id = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 RESULT = new InitProgramaNode(id);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("init_programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= init_programa BEGIN bloco END 
            {
              ProgramaNode RESULT =null;
		int inileft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int iniright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		InitProgramaNode ini = (InitProgramaNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int blocoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int blocoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		BlocoNode bloco = (BlocoNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = new ProgramaNode(ini, bloco);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // bloco ::= L_CHAVES instrucoes R_CHAVES 
            {
              BlocoNode RESULT =null;
		int instrsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int instrsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		InstrucoesNode instrs = (InstrucoesNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            RESULT = new BlocoNode((InstrucoesNode)instrs);
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloco",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instrucoes ::= instrucao 
            {
              InstrucoesNode RESULT =null;
		int instrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int instrright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		InstrucaoNode instr = (InstrucaoNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                InstrucoesNode instructions = new InstrucoesNode();
                instructions.addInstrucao((InstrucaoNode)instr);
                RESULT = instructions;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucoes",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instrucoes ::= instrucao instrucoes 
            {
              InstrucoesNode RESULT =null;
		int instrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int instrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		InstrucaoNode instr = (InstrucaoNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int instrsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int instrsright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		InstrucoesNode instrs = (InstrucoesNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                InstrucoesNode instructions = new InstrucoesNode();
                instructions.addInstrucao((InstrucaoNode)instr);
                instructions.addAllInstrucoes(((InstrucoesNode)instrs).instrucoes);
                RESULT = instructions;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucoes",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instrucao ::= FOR L_PARENTESES var_for VIRGULA condicoes VIRGULA atribuicao R_PARENTESES bloco 
            {
              InstrucaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // instrucao ::= WHILE L_PARENTESES condicoes R_PARENTESES bloco 
            {
              InstrucaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // instrucao ::= DO bloco WHILE L_PARENTESES condicoes R_PARENTESES PT_VIRGULA 
            {
              InstrucaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // instrucao ::= IF L_PARENTESES condicoes R_PARENTESES bloco 
            {
              InstrucaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // instrucao ::= IF L_PARENTESES condicoes R_PARENTESES bloco ELSE bloco 
            {
              InstrucaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // instrucao ::= FUNCTION ID L_PARENTESES parametros R_PARENTESES DOIS_PONTOS tipo L_CHAVES instrucoes RETURN var PT_VIRGULA R_CHAVES 
            {
              InstrucaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // instrucao ::= PROCEDURE ID L_PARENTESES parametros R_PARENTESES bloco 
            {
              InstrucaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // instrucao ::= PROC ID L_PARENTESES argumentos R_PARENTESES PT_VIRGULA 
            {
              InstrucaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // instrucao ::= inicializacao PT_VIRGULA 
            {
              InstrucaoNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		InicializacaoNode x = (InicializacaoNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // instrucao ::= atribuicao PT_VIRGULA 
            {
              InstrucaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // instrucao ::= declaracao PT_VIRGULA 
            {
              InstrucaoNode RESULT =null;
		int declleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int declright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		DeclaracaoNode decl = (DeclaracaoNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = decl;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("instrucao",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // condicoes ::= expressao 
            {
              CondicoesNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicoes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // condicoes ::= expressao operador_logico condicoes 
            {
              CondicoesNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicoes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // condicoes ::= expressao operador_comparacao condicoes 
            {
              CondicoesNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicoes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // parametros ::= parametro 
            {
              ParametrosNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // parametros ::= parametro VIRGULA parametros 
            {
              ParametrosNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // parametros ::= 
            {
              ParametrosNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // parametro ::= tipo ID 
            {
              ParametroNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // argumentos ::= expressao 
            {
              ArgumentosNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentos",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // argumentos ::= expressao VIRGULA argumentos 
            {
              ArgumentosNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentos",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // argumentos ::= 
            {
              ArgumentosNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("argumentos",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expressoes ::= expressao 
            {
              ExpressoesNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expressoes",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expressoes ::= expressao operador expressoes 
            {
              ExpressoesNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expressoes",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expressao ::= var 
            {
              ExpressaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expressao",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expressao ::= ID L_PARENTESES argumentos R_PARENTESES 
            {
              ExpressaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expressao",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expressao ::= var operador_aritmetico var 
            {
              ExpressaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expressao",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // var ::= ID 
            {
              VarNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo id = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new VarNode(id);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // var ::= literal 
            {
              VarNode RESULT =null;
		int litleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int litright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		LiteralNode lit = (LiteralNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new VarNode(lit); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // literal ::= INTEIRO 
            {
              LiteralNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo x = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LiteralNode(x); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("literal",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // literal ::= FLUTUANTE 
            {
              LiteralNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo x = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LiteralNode(x); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("literal",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // literal ::= CARACTERE 
            {
              LiteralNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo x = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LiteralNode(x); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("literal",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // literal ::= BOOL_TRUE 
            {
              LiteralNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo x = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LiteralNode(x); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("literal",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // literal ::= BOOL_FALSE 
            {
              LiteralNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo x = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new LiteralNode(x); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("literal",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // var_for ::= inicializacao 
            {
              VarForNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_for",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // var_for ::= atribuicao 
            {
              VarForNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_for",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // var_for ::= ID 
            {
              VarForNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_for",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // inicializacao ::= tipo ID IGUAL expressoes 
            {
              InicializacaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("inicializacao",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // atribuicao ::= ID operador_atribuicao expressoes 
            {
              AtribuicaoNode RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		TokenInfo id = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		OperadorAtribuicaoNode op = (OperadorAtribuicaoNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpressoesNode expr = (ExpressoesNode)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new AtribuicaoNode(id, op, expr); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("atribuicao",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // declaracao ::= tipo ID 
            {
              DeclaracaoNode RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TipoNode tipo = (TipoNode)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo id = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new DeclaracaoNode(tipo, id);
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // operador ::= operador_logico 
            {
              OperadorNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // operador ::= operador_aritmetico 
            {
              OperadorNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // operador ::= operador_comparacao 
            {
              OperadorNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // operador_logico ::= AND 
            {
              OperadorLogicoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_logico",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // operador_logico ::= OR 
            {
              OperadorLogicoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_logico",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // operador_comparacao ::= MENOR 
            {
              OperadorComparacaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_comparacao",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // operador_comparacao ::= MAIOR 
            {
              OperadorComparacaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_comparacao",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // operador_comparacao ::= IGUAL_IGUAL 
            {
              OperadorComparacaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_comparacao",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // operador_comparacao ::= DIFERENTE 
            {
              OperadorComparacaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_comparacao",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // operador_comparacao ::= MENOR_IGUAL 
            {
              OperadorComparacaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_comparacao",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // operador_comparacao ::= MAIOR_IGUAL 
            {
              OperadorComparacaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_comparacao",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // operador_aritmetico ::= ADD 
            {
              OperadorAritmeticoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_aritmetico",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // operador_aritmetico ::= SUB 
            {
              OperadorAritmeticoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_aritmetico",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // operador_aritmetico ::= MUL 
            {
              OperadorAritmeticoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_aritmetico",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // operador_aritmetico ::= DIV 
            {
              OperadorAritmeticoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_aritmetico",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // operador_atribuicao ::= IGUAL 
            {
              OperadorAtribuicaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_atribuicao",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // operador_atribuicao ::= ADD_IGUAL 
            {
              OperadorAtribuicaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_atribuicao",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // operador_atribuicao ::= SUB_IGUAL 
            {
              OperadorAtribuicaoNode RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("operador_atribuicao",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // tipo ::= TIPO_CHAR 
            {
              TipoNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo x = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // tipo ::= TIPO_FLUTUANTE 
            {
              TipoNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo x = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // tipo ::= TIPO_INTEIRO 
            {
              TipoNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo x = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // tipo ::= TIPO_BOOLEAN 
            {
              TipoNode RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TokenInfo x = (TokenInfo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
