
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 5;
  public static final int CARACTERE = 43;
  public static final int PT_VIRGULA = 11;
  public static final int PROGRAMA = 4;
  public static final int R_PARENTESES = 13;
  public static final int DIFERENTE = 19;
  public static final int BOOL_TRUE = 44;
  public static final int FOR = 38;
  public static final int DOIS_PONTOS = 10;
  public static final int VIRGULA = 9;
  public static final int AND = 25;
  public static final int IGUAL = 22;
  public static final int TIPO_BOOLEAN = 34;
  public static final int TIPO_FLUTUANTE = 33;
  public static final int OR = 26;
  public static final int L_CHAVES = 14;
  public static final int DIV = 30;
  public static final int BEGIN = 2;
  public static final int IF = 35;
  public static final int ID = 42;
  public static final int IGUAL_IGUAL = 18;
  public static final int EOF = 0;
  public static final int RETURN = 6;
  public static final int SUB_IGUAL = 24;
  public static final int MAIOR = 17;
  public static final int ADD_IGUAL = 23;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int TIPO_CHAR = 31;
  public static final int TIPO_INTEIRO = 32;
  public static final int ADD = 27;
  public static final int MENOR = 16;
  public static final int FLUTUANTE = 41;
  public static final int BOOL_FALSE = 45;
  public static final int ELSE = 36;
  public static final int INTEIRO = 40;
  public static final int WHILE = 37;
  public static final int END = 3;
  public static final int R_CHAVES = 15;
  public static final int PROC = 8;
  public static final int MENOR_IGUAL = 20;
  public static final int L_PARENTESES = 12;
  public static final int SUB = 28;
  public static final int MAIOR_IGUAL = 21;
  public static final int PROCEDURE = 7;
  public static final int DO = 39;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BEGIN",
  "END",
  "PROGRAMA",
  "FUNCTION",
  "RETURN",
  "PROCEDURE",
  "PROC",
  "VIRGULA",
  "DOIS_PONTOS",
  "PT_VIRGULA",
  "L_PARENTESES",
  "R_PARENTESES",
  "L_CHAVES",
  "R_CHAVES",
  "MENOR",
  "MAIOR",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MENOR_IGUAL",
  "MAIOR_IGUAL",
  "IGUAL",
  "ADD_IGUAL",
  "SUB_IGUAL",
  "AND",
  "OR",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "TIPO_CHAR",
  "TIPO_INTEIRO",
  "TIPO_FLUTUANTE",
  "TIPO_BOOLEAN",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "DO",
  "INTEIRO",
  "FLUTUANTE",
  "ID",
  "CARACTERE",
  "BOOL_TRUE",
  "BOOL_FALSE"
  };
}

