
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CARACTERE = 38;
  public static final int PT_VIRGULA = 7;
  public static final int R_PARENTESES = 9;
  public static final int DIFERENTE = 15;
  public static final int PRGRM_FIM = 3;
  public static final int PRGRM_INI = 2;
  public static final int BOOL_TRUE = 39;
  public static final int FOR = 33;
  public static final int DOIS_PONTOS = 6;
  public static final int VIRGULA = 5;
  public static final int AND = 21;
  public static final int IGUAL = 18;
  public static final int TIPO_FLUTUANTE = 29;
  public static final int OR = 22;
  public static final int L_CHAVES = 10;
  public static final int DIV = 26;
  public static final int IF = 30;
  public static final int ID = 37;
  public static final int IGUAL_IGUAL = 14;
  public static final int EOF = 0;
  public static final int SUB_IGUAL = 20;
  public static final int MAIOR = 13;
  public static final int ADD_IGUAL = 19;
  public static final int error = 1;
  public static final int MUL = 25;
  public static final int TIPO_CHAR = 27;
  public static final int TIPO_INTEIRO = 28;
  public static final int ADD = 23;
  public static final int MENOR = 12;
  public static final int FLUTUANTE = 36;
  public static final int BOOL_FALSE = 40;
  public static final int ELSE = 31;
  public static final int INTEIRO = 35;
  public static final int WHILE = 32;
  public static final int PRGRM_DEF = 4;
  public static final int R_CHAVES = 11;
  public static final int MENOR_IGUAL = 16;
  public static final int L_PARENTESES = 8;
  public static final int SUB = 24;
  public static final int MAIOR_IGUAL = 17;
  public static final int DO = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PRGRM_INI",
  "PRGRM_FIM",
  "PRGRM_DEF",
  "VIRGULA",
  "DOIS_PONTOS",
  "PT_VIRGULA",
  "L_PARENTESES",
  "R_PARENTESES",
  "L_CHAVES",
  "R_CHAVES",
  "MENOR",
  "MAIOR",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MENOR_IGUAL",
  "MAIOR_IGUAL",
  "IGUAL",
  "ADD_IGUAL",
  "SUB_IGUAL",
  "AND",
  "OR",
  "ADD",
  "SUB",
  "MUL",
  "DIV",
  "TIPO_CHAR",
  "TIPO_INTEIRO",
  "TIPO_FLUTUANTE",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "DO",
  "INTEIRO",
  "FLUTUANTE",
  "ID",
  "CARACTERE",
  "BOOL_TRUE",
  "BOOL_FALSE"
  };
}

